### ISSUE TITLE
No steam overlay

### ISSUE THREAD

**Issue by jobtalle** [jobtalle/Koi#189]
Steam overlay is not working.

**Comment by blaboing** [comment]
Found a tip [here](https://github.com/greenheartgames/greenworks/issues/50#issuecomment-475500422)
Started tinkering a bit and got overlay and screenshots working.

I don´t own the game on steam so but added it as non-steam game to try it out.
You can directly edit package.json in the KoiFarm.exe subfolder "\resources\app". no need to build with electron
- delete "--in-process-gpu --disable-direct-composition" from package.json
- add "--in-process-gpu --disable-direct-composition" to the steam launch options for Koi farm

Noticed that it didn´t always worked while at the menu or it had a few seconds delay but so far it worked flawless after hitting "start".
At the same issue as the above tip is a [comment](https://github.com/greenheartgames/greenworks/issues/50#issuecomment-224692245) that added 2 pixel sized canvas that get redrawn to get steam overlay working.
Didn´t try it yet but maybe it works better because there are moving fish/grass/bugs etc.

**Comment by blaboing** [comment]
Found an easier solution.

just add "--in-process-gpu --disable-direct-composition" to the steam launch options for Koi farm no need to edit package.json

**Comment by jobtalle** [comment]
@blaboing Thanks, that works for me as well! These parameters are already in the `package.json`, but that doesn't seem to do anything, so I'll make sure koi farm launches with these parameters through steam.
